name: keyclic_sdk_api
version: 2.1.0
description: The keyclic_sdk_api package is an implementation of the Keyclic API.
dependencies:
  http: ^0.12.0
  collection: ^1.14.11
  logging: ^0.11.3
author: Keyclic techies team <techies@keyclic.com>
environment:
  sdk: ">=2.2.2 <3.0.0"
homepage: https://keyclic.com
