name: keyclic_sdk_api
version: 1.39.4
description: The keyclic_sdk_api package is an implementation of the Keyclic API.
dependencies:
  http: '^0.12.0'
author: Keyclic techies team <techies@keyclic.com>
environment:
  sdk: ">=1.8.0 <3.0.0"
homepage: https://keyclic.com
