name: keyclic_sdk_api
version: 1.41.9
description: The keyclic_sdk_api package is an implementation of the Keyclic API.
dependencies:
  http: '^0.12.0'
  collection: '^1.14.12'
author: Keyclic techies team <techies@keyclic.com>
environment:
sdk: ">=2.2.2 <3.0.0"
homepage: https://keyclic.com
